const data = [
  "3d-boxes-background projects",
  "animated-countdown projects",
  "animated-navigation projects",
  "auto-text-effect projects",
  "background-slider projects",
  "blurry-loading projects",
  "button-ripple-effect projects",
  "content-placeholder projects",
  "custom-range-slider projects",
  "dad-jokes projects",
  "double-click-heart projects",
  "double-vertical-slider projects",
  "drag-n-drop projects",
  "drawing-app projects",
  "drink-water projects",
  "event-keycodes projects",
  "expanding-cards projects",
  "faq-collapse projects",
  "feedback-ui-design projects",
  "form-input-wave projects",
  "github-profiles projects",
  "good-cheap-fast projects",
  "hidden-search projects",
  "hoverboard projects",
  "image-carousel projects",
  "incrementing-counter projects",
  "insect-catch-game projects",
  "kinetic-loader projects",
  "live-user-filter projects",
  "mobile-tab-navigation projects",
  "movie-app projects",
  "netflix-mobile-navigation projects",
  "notes-app projects",
  "password-generator projects",
  "password-strength-background projects",
  "pokedex projects/progress-steps projects",
  "quiz-app projects/random-choice-picker projects",
  "random-image-generator projects",
  "rotating-nav-animation projects",
  "scroll-animation projects",
  "simple-timer projects",
  "sound-board projects",
  "split-landing-page projects",
  "sticky-navigation projects",
  "testimonial-box-switcher projects",
  "theme-clock projects",
  "toast-notification projects",
  "todo-list projects",
  "verify-account-ui"
];

export default data;
